global:
  scrape_interval: 10s  # Scrape every 10 seconds

scrape_configs:
  - job_name: 'flask-app'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['flask_app:8000']  # Flask app's metrics endpoint